import { useState } from 'react'
import { ArrowUpRight, BadgeCheck, Building2, ChevronRight, ClipboardCheck, Home, Leaf, MapPin, Plus, Snowflake, Wind } from 'lucide-react'
import { SiteLayout, WhatsAppIcon } from '@/components/SiteLayout'
import { QuoteDialog } from '@/components/QuoteDialog'
import { faqs, phone, phoneHref, sectionPages, services, whatsappUrl } from '@/lib/site'
import type { SectionId } from '@/lib/site'

const serviceIcons = [Wind, Home, Building2]

export function SectionPage({ sectionId }: { sectionId: SectionId }) {
  const [quoteOpen, setQuoteOpen] = useState(false)
  const page = sectionPages.find(page => page.id === sectionId)!
  return <SiteLayout>
    <main id="conteudo" className="section-page">
      <nav className="breadcrumb container" aria-label="Localização"><a href="/">Início</a><ChevronRight size={13}/><span aria-current="page">{page.label}</span></nav>
      {sectionId === 'servicos' && <section id="servicos" className="services-section section container"><div className="section-heading"><div><span className="eyebrow">SOLUÇÕES PARA O SEU AMBIENTE</span><h1>Cada espaço, um jeito<br/>de ficar mais confortável.</h1></div><p>Da sala de casa ao seu local de trabalho.<br/>Encontre a instalação que faz sentido para você.</p></div>
        <div className="services-grid">{services.map((service, index) => { const Icon = serviceIcons[index]; return <a className={`service-card service-card-${index}`} href={`/servicos/${service.slug}`} key={service.slug}><div className="service-card-top"><span className="service-icon"><Icon size={27} strokeWidth={1.6}/></span><span className="card-number">0{index + 1}</span></div><div><span className="service-kicker">{index === 0 ? 'O BÁSICO BEM-FEITO' : index === 1 ? 'SEU REFÚGIO, MAIS AGRADÁVEL' : 'CONFORTO TAMBÉM É TRABALHO'}</span><h3>{service.label}</h3><p>{service.description}</p></div><div className="service-card-link">Conhecer o serviço <span><ArrowUpRight size={19}/></span></div></a> })}</div>
      </section>}

      {sectionId === 'por-que-argelado' && <section id="por-que-argelado" className="why-section"><div className="container why-grid"><div className="why-title"><span className="eyebrow">É BOM CONTAR COM QUEM ESTÁ PERTO</span><h1>Instalar é só o começo.<br/><span>O cuidado faz<br/>a diferença.</span></h1><p>Na Argelado, cada instalação começa com uma conversa. Entendemos o seu espaço para combinar uma solução, sem promessas genéricas e sem surpresas no escopo.</p><a href={whatsappUrl()} target="_blank" rel="noopener noreferrer" className="text-link">Vamos conversar <ArrowUpRight size={19}/></a></div><div className="why-features"><div><span><ClipboardCheck size={23}/></span><section><h3>Seu ambiente vem primeiro</h3><p>Avaliamos as informações do local e do equipamento antes de definir o serviço.</p></section></div><div><span><BadgeCheck size={23}/></span><section><h3>Clareza do início ao fim</h3><p>O orçamento e os detalhes da instalação são combinados antes do agendamento.</p></section></div><div><span><Leaf size={23}/></span><section><h3>Cuidado com o seu espaço</h3><p>Atenção ao posicionamento do aparelho, à infraestrutura e ao acabamento.</p></section></div><div><span><MapPin size={23}/></span><section><h3>Atendimento de verdade, em Canoas</h3><p>Contato direto pelo WhatsApp para tirar dúvidas e organizar a sua instalação.</p></section></div></div></div></section>}

      {sectionId === 'como-funciona' && <section id="como-funciona" className="section container process-section"><div className="section-heading"><div><span className="eyebrow">SIMPLES, DO JEITO QUE DEVE SER</span><h1>Do primeiro “oi”<br/>ao seu novo clima.</h1></div><button className="button button-outline" type="button" onClick={() => setQuoteOpen(true)}>Começar agora <ArrowUpRight size={17}/></button></div><div className="process-grid"><div className="process-step"><span className="step-number">01</span><h3>Conte o que você precisa</h3><p>Fale com a gente pelo WhatsApp. Envie seu bairro, o modelo do aparelho e fotos do ambiente.</p></div><div className="process-step"><span className="step-number">02</span><h3>Receba seu orçamento</h3><p>Conversamos sobre as condições do local e combinamos o escopo e o valor do serviço.</p></div><div className="process-step"><span className="step-number">03</span><h3>Combine a instalação</h3><p>Com o orçamento aprovado, definimos o agendamento e os detalhes para atender você.</p></div></div></section>}

      {sectionId === 'atendimento' && <section className="local-section container"><div className="local-content"><span className="eyebrow"><MapPin size={14}/> DE CANOAS, PARA CANOAS</span><h1>Seu conforto tem<br/>atendimento local.</h1><p>Precisa instalar um ar-condicionado em Canoas, RS? A Argelado conecta você à solução para sua casa ou empresa. Envie seu bairro e conte sobre o ambiente para iniciar o atendimento.</p><a href={whatsappUrl('Olá, Argelado! Moro em Canoas e gostaria de confirmar o atendimento no meu bairro.')} className="text-link" target="_blank" rel="noopener noreferrer">Consultar atendimento no meu bairro <ArrowUpRight size={18}/></a></div><div className="local-art" aria-hidden="true"><div className="local-ring ring-one"/><div className="local-ring ring-two"/><div className="local-ring ring-three"/><span className="local-pin"><MapPin size={32} strokeWidth={1.7}/></span><div className="local-map-label"><strong>Canoas</strong><span>Rio Grande do Sul</span></div><span className="map-coordinate">29°55′ S · 51°11′ O</span></div></section>}

      {sectionId === 'duvidas' && <section id="duvidas" className="section container faq-section"><div className="faq-heading"><span className="eyebrow">PODE PERGUNTAR</span><h1>Menos dúvidas.<br/>Mais tranquilidade.</h1><p>O que você precisa saber antes<br/>de instalar seu ar-condicionado.</p><a className="text-link" href={whatsappUrl('Olá, Argelado! Tenho uma dúvida sobre instalação de ar-condicionado.')} target="_blank" rel="noopener noreferrer">Tenho outra dúvida <ArrowUpRight size={17}/></a></div><div className="faq-list">{faqs.map(faq => <details key={faq.question}><summary>{faq.question}<Plus size={19}/></summary><p>{faq.answer}</p></details>)}</div></section>}

      {sectionId === 'contato' && <section className="final-cta container"><div className="cta-snowflake" aria-hidden="true"><Snowflake/></div><div><span className="eyebrow">MAIS CONFORTO ESTÁ A UMA CONVERSA</span><h1>Vamos deixar o seu<br/>ambiente mais agradável?</h1><p>Conte com a Argelado para instalar seu ar-condicionado em Canoas.</p></div><div className="final-cta-action"><button className="button button-light" type="button" onClick={() => setQuoteOpen(true)}><WhatsAppIcon/> Quero meu orçamento <ArrowUpRight size={18}/></button><span>Direto no WhatsApp. Sem complicação.</span></div></section>}
      {sectionId === 'contato' && <p className="contact-details container">Prefere ligar? <a href={phoneHref}>{phone}</a>. A mensagem de orçamento é preparada no navegador; você confirma o envio no WhatsApp.</p>}
      <section className="article-related container"><h2>Continue explorando</h2><div className="article-related-links">{sectionPages.filter(other => other.id !== sectionId).map(other => <a key={other.id} href={other.path}>{other.label}<ArrowUpRight size={17}/></a>)}<a href="/guia/instalacao-ar-condicionado">Guia de instalação<ArrowUpRight size={17}/></a></div></section>
    </main>
    <QuoteDialog open={quoteOpen} onClose={() => setQuoteOpen(false)}/>
  </SiteLayout>
}
