/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DuvidasRouteImport } from './routes/duvidas'
import { Route as PorQueArgeladoRouteImport } from './routes/por-que-argelado'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as GuiaInstalacaoArCondicionadoRouteImport } from './routes/guia.instalacao-ar-condicionado'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DuvidasRoute = DuvidasRouteImport.update({
  id: '/duvidas',
  path: '/duvidas',
  getParentRoute: () => rootRouteImport,
} as any)
const PorQueArgeladoRoute = PorQueArgeladoRouteImport.update({
  id: '/por-que-argelado',
  path: '/por-que-argelado',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaInstalacaoArCondicionadoRoute =
  GuiaInstalacaoArCondicionadoRouteImport.update({
    id: '/guia/instalacao-ar-condicionado',
    path: '/guia/instalacao-ar-condicionado',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/duvidas': typeof DuvidasRoute
  '/por-que-argelado': typeof PorQueArgeladoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/guia/instalacao-ar-condicionado': typeof GuiaInstalacaoArCondicionadoRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/duvidas': typeof DuvidasRoute
  '/por-que-argelado': typeof PorQueArgeladoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/guia/instalacao-ar-condicionado': typeof GuiaInstalacaoArCondicionadoRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/duvidas': typeof DuvidasRoute
  '/por-que-argelado': typeof PorQueArgeladoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/guia/instalacao-ar-condicionado': typeof GuiaInstalacaoArCondicionadoRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimento'
    | '/como-funciona'
    | '/contato'
    | '/duvidas'
    | '/por-que-argelado'
    | '/privacidade'
    | '/guia/instalacao-ar-condicionado'
    | '/servicos/$slug'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendimento'
    | '/como-funciona'
    | '/contato'
    | '/duvidas'
    | '/por-que-argelado'
    | '/privacidade'
    | '/guia/instalacao-ar-condicionado'
    | '/servicos/$slug'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/atendimento'
    | '/como-funciona'
    | '/contato'
    | '/duvidas'
    | '/por-que-argelado'
    | '/privacidade'
    | '/guia/instalacao-ar-condicionado'
    | '/servicos/$slug'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  DuvidasRoute: typeof DuvidasRoute
  PorQueArgeladoRoute: typeof PorQueArgeladoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  GuiaInstalacaoArCondicionadoRoute: typeof GuiaInstalacaoArCondicionadoRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duvidas': {
      id: '/duvidas'
      path: '/duvidas'
      fullPath: '/duvidas'
      preLoaderRoute: typeof DuvidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/por-que-argelado': {
      id: '/por-que-argelado'
      path: '/por-que-argelado'
      fullPath: '/por-que-argelado'
      preLoaderRoute: typeof PorQueArgeladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/instalacao-ar-condicionado': {
      id: '/guia/instalacao-ar-condicionado'
      path: '/guia/instalacao-ar-condicionado'
      fullPath: '/guia/instalacao-ar-condicionado'
      preLoaderRoute: typeof GuiaInstalacaoArCondicionadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  DuvidasRoute: DuvidasRoute,
  PorQueArgeladoRoute: PorQueArgeladoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  GuiaInstalacaoArCondicionadoRoute: GuiaInstalacaoArCondicionadoRoute,
  ServicosSlugRoute: ServicosSlugRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
